services:
  openvpn:
    build:
      context: .
      dockerfile: Dockerfile.openvpn
    image: openvpn:local
    command: /etc/openvpn/setup/configure.sh
    environment:
      OVPN_SERVER_NET: "192.168.100.0"
      OVPN_SERVER_MASK: "255.255.255.0"
      OVPN_PASSWD_AUTH: "true"

      # --- 2FA ---
      OVPN_2FA: "true"
      GOOGLE_2FA_AUTH_DIR: "/etc/google-auth"

    cap_add:
      - NET_ADMIN

    ports:
      - 7777:1194   # OpenVPN
      - 8080:8080   # ovpn-admin (por network_mode)

    volumes:
      # PKI / CCD
      - ./easyrsa_master:/etc/openvpn/easyrsa
      - ./ccd_master:/etc/openvpn/ccd

      # --- 2FA ---
      - ./setup/google-auth/google-auth.sh:/etc/openvpn/google-auth.sh:ro
      - ./google-auth:/etc/google-auth


  ovpn-admin:
    build:
      context: .
      dockerfile: Dockerfile.ovpn-admin
    image: ovpn-admin:local
    command: /app/ovpn-admin

    environment:
      OVPN_DEBUG: "true"
      OVPN_VERBOSE: "true"

      OVPN_NETWORK: "192.168.100.0/24"
      OVPN_CCD: "true"
      OVPN_CCD_PATH: "/mnt/ccd"

      EASYRSA_PATH: "/mnt/easyrsa"
      OVPN_INDEX_PATH: "/mnt/easyrsa/pki/index.txt"

      OVPN_SERVER: "127.0.0.1:7777:tcp"

      OVPN_AUTH: "true"
      OVPN_AUTH_DB_PATH: "/mnt/easyrsa/pki/users.db"

      LOG_LEVEL: "debug"

      # --- 2FA ---
      OVPN_2FA: "true"
      GOOGLE_2FA_AUTH_DIR: "/etc/google-auth"

    network_mode: service:openvpn

    volumes:
      - ./easyrsa_master:/mnt/easyrsa
      - ./ccd_master:/mnt/ccd
      - ./google-auth:/etc/google-auth
      - ./setup/google-auth/google-auth.sh:/etc/openvpn/google-auth.sh:ro
